from flask import Flask, request, jsonify
from flask_cors import CORS
import sqlite3
from datetime import date, datetime

from AI.pipeline import search_and_process_internships


app = Flask(__name__)
CORS(app)

DATABASE = "internflow.db"


# =========================================
# DATABASE CONNECTION
# =========================================

def get_db_connection():
    connection = sqlite3.connect(DATABASE)
    connection.row_factory = sqlite3.Row
    return connection


# =========================================
# SAVE AI INTERNSHIP RESULT
# =========================================

def save_internship(internship):

    connection = get_db_connection()
    cursor = connection.cursor()

    # Check if this internship already exists
    existing = cursor.execute("""
        SELECT id
        FROM internships
        WHERE company = ?
        AND role = ?
        AND location = ?
    """, (
        internship.get("company"),
        internship.get("role"),
        internship.get("location")
    )).fetchone()

    # Don't save duplicates
    if existing:
        connection.close()

        # Return the existing internship's ID
        return existing["id"]

    cursor.execute("""
        INSERT INTO internships
        (company, role, skills, location, stipend, deadline,
         eligibility, application_link, match_percentage)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        internship.get("company"),
        internship.get("role"),

        # Convert skills list into a string
        ", ".join(internship.get("skills", []))
        if isinstance(internship.get("skills"), list)
        else internship.get("skills"),

        internship.get("location"),
        internship.get("stipend"),
        internship.get("deadline"),
        internship.get("eligibility"),

        # AI uses application_url
        # Database uses application_link
        internship.get("application_url"),

        # Match percentage calculated by AI matching
        internship.get("match_percentage")
    ))

    # Get the ID generated by SQLite
    internship_id = cursor.lastrowid

    connection.commit()
    connection.close()

    return internship_id


# =========================================
# SAVE STUDENT PREFERENCES
# =========================================

@app.route("/save-preferences", methods=["POST"])
def save_preferences():

    data = request.get_json()

    if not data:
        return jsonify({
            "error": "No data received"
        }), 400

    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        INSERT INTO student_preferences (
            name,
            email,
            student_skills,
            preferred_domain,
            internship_type,
            locations,
            minimum_stipend,
            maximum_duration,
            payment_type,
            work_mode,
            study_year,
            availability,
            deadline_preference,
            company_preference,
            email_frequency
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

        ON CONFLICT(email) DO UPDATE SET
            name = excluded.name,
            student_skills = excluded.student_skills,
            preferred_domain = excluded.preferred_domain,
            internship_type = excluded.internship_type,
            locations = excluded.locations,
            minimum_stipend = excluded.minimum_stipend,
            maximum_duration = excluded.maximum_duration,
            payment_type = excluded.payment_type,
            work_mode = excluded.work_mode,
            study_year = excluded.study_year,
            availability = excluded.availability,
            deadline_preference = excluded.deadline_preference,
            company_preference = excluded.company_preference,
            email_frequency = excluded.email_frequency
    """, (
        data.get("name"),
        data.get("email"),
        ",".join(data.get("student_skills", [])),
        data.get("preferred_domain"),
        data.get("internship_type"),
        ",".join(data.get("locations", [])),
        data.get("minimum_stipend"),
        data.get("maximum_duration"),
        data.get("payment_type"),
        data.get("work_mode"),
        data.get("study_year"),
        data.get("availability"),
        data.get("deadline_preference"),
        data.get("company_preference"),
        data.get("email_frequency")
    ))

    connection.commit()
    connection.close()

    return jsonify({
        "message": "Preferences saved successfully!"
    })


# =========================================
# AI INTERNSHIP SEARCH
# =========================================

@app.route("/search-internships", methods=["POST"])
def search_internships():

    data = request.get_json()

    if not data:
        return jsonify({
            "error": "No data received"
        }), 400

    student_skills = data.get("student_skills", [])
    preferred_domain = data.get("preferred_domain", "")
    locations = data.get("locations", [])
    minimum_stipend = data.get("minimum_stipend", 0)

    if not student_skills:
        return jsonify({
            "error": "Student skills are required"
        }), 400

    if not preferred_domain:
        return jsonify({
            "error": "Preferred domain is required"
        }), 400

    if not locations:
        return jsonify({
            "error": "At least one location is required"
        }), 400

    all_results = []

    # Search separately for each selected location
    for location in locations:

        results = search_and_process_internships(
            student_skills,
            preferred_domain,
            location,
            minimum_stipend
        )

        if results:

            for internship in results:

                internship_id = save_internship(internship)

                if internship_id:
                    print(
                        f"Saved/Found in database: "
                        f"{internship.get('company')} - "
                        f"{internship.get('role')} "
                        f"(ID: {internship_id})"
                    )

                # Add database ID to the result sent to frontend
                internship["id"] = internship_id

                all_results.append(internship)

    return jsonify({
        "count": len(all_results),
        "internships": all_results
    })


# =========================================
# ADD INTERNSHIP MANUALLY
# =========================================

@app.route("/internships", methods=["POST"])
def add_internship():

    data = request.get_json()

    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("""
        INSERT INTO internships
        (company, role, skills, location, stipend, deadline,
         eligibility, application_link)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        data.get("company"),
        data.get("role"),
        data.get("skills"),
        data.get("location"),
        data.get("stipend"),
        data.get("deadline"),
        data.get("eligibility"),
        data.get("application_link")
    ))

    connection.commit()
    connection.close()

    return jsonify({
        "message": "Internship added successfully!"
    }), 201


# =========================================
# GET ALL INTERNSHIPS
# =========================================

@app.route("/internships", methods=["GET"])
def get_internships():

    connection = get_db_connection()

    internships = connection.execute(
        "SELECT * FROM internships"
    ).fetchall()

    connection.close()

    return jsonify([
        dict(internship)
        for internship in internships
    ])


# =========================================
# GET SAVED INTERNSHIPS
# =========================================

@app.route("/saved-internships", methods=["GET"])
def get_saved_internships():

    connection = get_db_connection()

    internships = connection.execute(
        "SELECT * FROM internships WHERE saved = 1"
    ).fetchall()

    connection.close()

    return jsonify([
        dict(internship)
        for internship in internships
    ])


# =========================================
# UPDATE APPLICATION STATUS
# =========================================

@app.route("/internships/<int:internship_id>/status", methods=["PUT"])
def update_status(internship_id):

    data = request.get_json()

    new_status = data.get("status")

    connection = get_db_connection()

    cursor = connection.cursor()

    cursor.execute(
        "UPDATE internships SET status = ? WHERE id = ?",
        (new_status, internship_id)
    )

    connection.commit()
    connection.close()

    return jsonify({
        "message": "Application status updated successfully!"
    })


# =========================================
# SAVE INTERNSHIP
# =========================================

@app.route("/internships/<int:internship_id>/save", methods=["PUT"])
def save_internship_for_student(internship_id):

    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute(
        "UPDATE internships SET saved = 1 WHERE id = ?",
        (internship_id,)
    )

    connection.commit()
    connection.close()

    return jsonify({
        "message": "Internship saved successfully!"
    })


# =========================================
# UPCOMING DEADLINES
# =========================================

@app.route("/internships/deadlines", methods=["GET"])
def upcoming_deadlines():

    connection = get_db_connection()

    internships = connection.execute(
        "SELECT * FROM internships"
    ).fetchall()

    connection.close()

    today = date.today()

    upcoming = []

    for internship in internships:

        # Ignore internships with no deadline
        if not internship["deadline"]:
            continue

        try:
            deadline = datetime.strptime(
                internship["deadline"],
                "%Y-%m-%d"
            ).date()
        except ValueError:
            continue

        days_left = (deadline - today).days

        if 0 <= days_left <= 7:

            internship_data = dict(internship)

            internship_data["days_left"] = days_left

            upcoming.append(internship_data)

    return jsonify(upcoming)


# =========================================
# RUN SERVER
# =========================================

if __name__ == "__main__":
    app.run(debug=True)